// the id's as we can see in the models the ss i have taken are no need to be decleared as the id is generated by the 
// mongoose itself so we dont have to mentioned id 




// we will also be using  a dependency called bcrypt 
// npm install bcrypt 
// this is also a dependency which is called bcryptjs which is also a dependency works same like bcrypt 
// but there is a difference between both almost working is same too 

// bcrypt is a library for nodejs 
// while
// bcryptjs is a optimized bcrypt in plain js with zero dependencies.
// this bcrypt help to hash our password 
// this handales all the encrypting and decrypting of the password when needed

// jwt = json web token  
// when we we are talking about tokens this helps there like here in this Schema 

// both bcrypt and jwt-jsonwebtoken makes token and are based on cryptography 
// for example we can see in jwt.io website how tokens are 


// direct encryption is impossible here so we need help from mongoose hooks 
// eg- a (pre) hook which is a middleware what this does is when our data is going to be saved just before it like we want 
// to encrypt our password we can do it using this hook 


import mongoose, {Schema} from "mongoose";
// here we have direclty imported Schema from the mongoose so we use Schema rather than mongoose.Schema
import jwt from "jsonwebtoken"
import bcrypt from "bcrypt"

const userSchema = new Schema({

    username: {
        type: String,
        required: true,
        unique: true,
        lowercase: true,
        trim: true,
        index: true
        // index true we do for those which are searcable items like username will be one of the most searchable thing
    },

    email: {
        type: String,
        required: true,
        unique: true,
        lowercase: true,
        trim: true
    },

    fullName: {
        type: String,
        required: true,
        trim: true,
        index: true
    },

    avatar: {
        type: String, // using cloudinary services ie its url 
        required: true,
    },

    coverImage: {
        type: String, // using cloudinary services ie its url
    },

    password: { // one of the important challanges
        type: String,
        required: [true, "Password is required"]
    },

    watchHistory: [// array of video 
        {
            type: Schema.Types.ObjectId,
            ref: "Video"
        }
    ],
    refreshToken: {
        type: String
    }

}, {timestamps: true})


// here save is for whenever we are saving data just vefore it run this middleware 
// we dont use arrow function here as arrow function dont use this feature and we want a particula user who is saving 
// his or her data so for that we write a mannual function there 
// we write async function cuz we know we are talking with the database and also algo runs takes time cpu processing 
// we will be using next as we know when we deal with middleware we use next keyword so that when the middleware 
// has completed its work we can goe to next part or the next middleware 

// userSchema.pre("save", async function (next) {
//     this.password = bcrypt.hash(this.password, 10);
//     next()
//     // now we have created a problem as now like if we change our avatar in user the password again changes as this will 
//     // run before doing any changes in our database which will cause the chage of password bcz we are again encrypting 
//     // the same password which we dont want as there will be already  user's password encrypted and we dont
//     // want it to change unnecessarily
//     // so we want that when we are doing things with the password field than only run this otherwise ignore it 

// });

// userSchema.pre("save", async function (next) {
//     this.password = bcrypt.hash(this.password, 10);
//     // 10 → how much computational work bcrypt should perform
//     // 10 is the salt rounds (cost factor) used by bcrypt.
//     // higher the number more secure will be against brute forse attacks but will be slower 
//     // slower here means bcrypt will take more time to encrypt it 
//     // as you increase the number, the computational cost increase
//     // Computational cost simply means how much work the computer has to do to complete an operation.

//     next()
// });

// so to only make this method run when we chage password we do 

userSchema.pre("save", async function(next) 
{
    if(this.isModified("password"))
    {
        this.password = bcrypt.hash(this.password, 12);
        next();
        // this next is for so that we can now go to next middleware or go next bcz with this middleware our work is done 
    }
    
})

// as mongoose give us in build methods and give us freedom to make our own methods we can make a method to check weather a 
// user is a vaild user or not by checking its password as we know we have encrypted tthe password so 
// in that method we are gonna decrypt the password and check with the user's password the user has given 
// currently 

// this is how to make a custom method
userSchema.methods.isPasswordCorrect = async function(password)// the password user has given rn
{
    // this too takes time so we use await bcz this is cryptography which takes time 
    return await bcrypt.compare(password, this.password);
    // this bcrypt library has its own in it to check password so this is how we do it 
    // first thing we pass is the current ppassword given by the user 2nd thing is the encrypted password
    // this library compare both and than return a boolean value 
}

// we can also make a access token generate method too here 

userSchema.methods.generateAccessTokent = async function()
{
    return await jwt.sign( // here this jwt.sign return access token when it is ready here 
        {
            _id: this._id,
            email: this.email,
            username: this.username,
            fullName: this.fullName
            // this first fullname is the name of the payload key and the second this.fullName is what coming from the database
            // so this.fullName in this "fullName" must match with "fullName" which is stored in the db we cant use "fullname"
        },
        // another thigit wants is the access token secret 
        process.env.ACCESS_TOKEN_SECRET,
        {
            expiresIn: process.env.ACCESS_TOKEN_EXPIRY
            // this is when our token will be expired
        },
    )
    // jwt has a sign method which generate token we also give sign a payload which can be string or an object 
}
// and just like our access token our refresh token is also generated like this 
userSchema.methods.generateRefreshToken = async function()
{
    return await jwt.sign( // here this jwt.sign return refresh token when it is ready here 
        {
            _id: this._id
            // this refresh token has less info as it gets refreshed time to time so we dont store that much data in it 
        },
        process.env.REFRESH_TOKEN_SECRET,
        {
            expiresIn: process.env.REFRESH_TOKEN_EXPIRY
        },
    )
}

export const User = mongoose.model("User", userSchema);












































// // using without any comments here we are 

// import mongoose, {Schema} from "mongoose";
// import jwt from "jsonwebtoken"
// import bcrypt from "bcrypt"

// const userSchema = new Schema({

//     username: {
//         type: String,
//         required: true,
//         unique: true,
//         lowercase: true,
//         trim: true,
//         index: true
//     },

//     email: {
//         type: String,
//         required: true,
//         unique: true,
//         lowercase: true,
//         trim: true
//     },

//     fullName: {
//         type: String,
//         required: true,
//         trim: true,
//         index: true
//     },

//     avatar: {
//         type: String,
//         required: true,
//     },

//     coverImage: {
//         type: String, 
//     },

//     password: {
//         type: String,
//         required: [true, "Password is required"]
//     },

//     watchHistory: [
//         {
//             type: Schema.Types.ObjectId,
//             ref: "Video"
//         }
//     ],
//     refreshToken: {
//         type: String
//     }

// }, {timestamps: true})


// userSchema.pre("save", async function(next) 
// {
//     if(this.isModified("password"))
//     {
//         this.password = bcrypt.hash(this.password, 12);
//         next();
//     }
    
// })

// userSchema.methods.isPasswordCorrect = async function(password)
// {
//     return await bcrypt.compare(password, this.password);
// }


// userSchema.methods.generateAccessTokent = async function()
// {
//     return await jwt.sign( 
//         {
//             _id: this._id,
//             email: this.email,
//             username: this.username,
//             fullName: this.fullName
//         },
//         process.env.ACCESS_TOKEN_SECRET,
//         {
//             expiresIn: process.env.ACCESS_TOKEN_EXPIRY
//         },
//     )
// }
// userSchema.methods.generateRefreshToken = async function()
// {
//     return await jwt.sign( 
//         {
//             _id: this._id
//         },
//         process.env.REFRESH_TOKEN_SECRET,
//         {
//             expiresIn: process.env.REFRESH_TOKEN_EXPIRY
//         },
//     )
// }

// export const User = mongoose.model("User", userSchema);


